services:
  oxspires_recon:
    container_name: spires_container
    build:
      context: ../..
      dockerfile: .docker/recon/Dockerfile
      target: deploy
      args:
        - USERNAME=${USERNAME}
        - UID=${UID}
        - GID=${GID}
        - DOCKER_HOME_DIR=${DOCKER_HOME_DIR}
        - DOCKER_WORKDIR=${DOCKER_WORKDIR}
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    runtime: nvidia
    network_mode: "host"
    tty: true
    volumes:
      - ../..:${DOCKER_WORKDIR}/
      - ${HOST_DATA_DIR}:${DOCKER_DATA_DIR}
      - ~/.netrc:/home/docker_dev/.netrc
      - ~/.cache/huggingface/token:/home/docker_dev/.cache/huggingface/token
