services:
  oxspires_recon:
    container_name: spires_container
    build:
      context: ../..
      dockerfile: .docker/recon/Dockerfile
      target: deploy
      args:
        - USERNAME=${USERNAME}
        - UID=${UID}
        - GID=${GID}
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    runtime: nvidia
    network_mode: "host"
    tty: true
    volumes:
      - ../:${SPIRES_DIR}/
      - ${HOST_SPIRES_DATA_DIR}:${SPIRES_DATA_DIR}
      - ~/.netrc:/home/docker_dev/.netrc
      - ~/.cache/huggingface/token:/home/docker_dev/.cache/huggingface/token
