repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.8.1
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
        types_or: [python, pyi, jupyter]

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.8  # Replace with the latest version
    hooks:
      - id: clang-format
        args: ["--style={BasedOnStyle: LLVM, ColumnLimit: 120}"]  # This makes it use your .clang-format file, if present
