version: '3'

vars:
  DOCKER_COMPOSE_PATH: .docker/oxspires/docker-compose.yml

tasks:
  # ── Docker ────────────────────────────────────────────────────────────────

  docker_build_run:
    desc: Build and run development Docker container -- e.g. task docker_build_run -- task test
    cmds:
      - mkdir -p data outputs runs
      - DOCKER_UID=$(id -u) DOCKER_GID=$(id -g) docker compose -f {{.DOCKER_COMPOSE_PATH}} run --build --rm oxspires_utils bash -c "source ~/.bashrc && {{.CLI_ARGS | default "bash"}}"

  docker_run:
    desc: Run a command in Docker without rebuilding -- e.g. task docker_run -- python3 script.py
    cmds:
      - mkdir -p data outputs runs
      - DOCKER_UID=$(id -u) DOCKER_GID=$(id -g) docker compose -f {{.DOCKER_COMPOSE_PATH}} run --rm oxspires_utils bash -c "source ~/.bashrc && {{.CLI_ARGS | default "bash"}}"

  # ── Scripts ──────────────────────────────────────────────────────────────

  download:
    desc: Download dataset using patterns from config -- e.g. task download -- --patterns sequences/foo1/* sequences/foo2/*
    cmds:
      - "python scripts/dataset_download.py {{.CLI_ARGS}}"

  # ── Dev ───────────────────────────────────────────────────────────────────

  install:
    desc: Install the package in development mode
    cmds:
      - pip install -e .

  install_with_cpp:
    desc: Install the package with C++ bindings
    cmds:
      - BUILD_CPP=1 pip install -e .

  ruff:
    desc: Run Ruff linter and formatter
    cmds:
      - ruff check --fix --config pyproject.toml
      - ruff format --config pyproject.toml

  test:
    desc: Run all tests
    cmds:
      - pytest
