localisation_benchmark:
  # package_dir: "/home/mice85/oxford-lab/labrobotica/algorithms/oxford_spires_dataset"
  dataset_folder: "~/oxford_spires_dataset/data/" 
  flag_is_all: false # If true it rund all the sequences in the 'dataset_dir'. If false it runs the sequences in 'list_sec'
  flag_download_data: false

  list_sec: [
              # "sequences/2024-03-12-keble-college-02",
              # "sequences/2024-03-12-keble-college-03",
              # "sequences/2024-03-12-keble-college-04",
              # "sequences/2024-03-12-keble-college-05",
              # "sequences/2024-03-13-observatory-quarter-01",
              # "sequences/2024-03-13-observatory-quarter-02",
              # "sequences/2024-03-14-blenheim-palace-01",
              # "sequences/2024-03-14-blenheim-palace-02",
              # "sequences/2024-03-14-blenheim-palace-05",
              # "sequences/2024-03-18-christ-church-01",
              "sequences/2024-03-18-christ-church-02",
              # "sequences/2024-03-18-christ-church-03",
              # "sequences/2024-03-20-christ-church-05",
              # "sequences/2024-05-20-bodleian-library-02"
              ]
  
  run_fast_lio_slam: true