version: '3'

services:
  oxspires_utils:
    build:
      context: ../..
      dockerfile: .docker/oxspires/Dockerfile
      target: final
      args:
        - USERNAME=${USERNAME}
        - UID=${UID}
        - GID=${GID}
        - DOCKER_HOME_DIR=${DOCKER_HOME_DIR}
        - DOCKER_WORKDIR=${DOCKER_WORKDIR}
    runtime: nvidia
    tty: true
    volumes:
      - ../../scripts:${DOCKER_WORKDIR}/scripts
      - ${HOST_DATA_DIR}:${DOCKER_DATA_DIR}
