version: '3'

services:
  oxspires_utils:
    build:
      context: ../..
      dockerfile: .docker/oxspires/Dockerfile
      target: base
      args:
        - USERNAME=${USERNAME}
        - UID=${UID}
        - GID=${GID}
        - HOME_DIR=${HOME_DIR}
        - OXSPIRES_DIR=${OXSPIRES_DIR}
    runtime: nvidia
    tty: true
    volumes:
      - ../../scripts:/home/docker_dev/oxford_spires_dataset/scripts
      - ~/.cache/huggingface/token:/home/docker_dev/.cache/huggingface/token
      - ${HOST_OXSPIRES_DATA_DIR}:${OXSPIRES_DATA_DIR}
