version: '3'

services:
  oxspires_utils:
    image: oxspires_utils:latest
    build:
      context: ../..
      dockerfile: .docker/oxspires/Dockerfile
      target: dev
      args:
        - DOCKER_USERNAME=${DOCKER_USERNAME}
        - DOCKER_UID=${DOCKER_UID}
        - DOCKER_GID=${DOCKER_GID}
        - DOCKER_HOME_DIR=${DOCKER_HOME_DIR}
    runtime: nvidia
    stdin_open: true
    tty: true
    volumes:
      - ../../scripts:${DOCKER_HOME_DIR}/oxford_spires_dataset/scripts
      - ../../configs:${DOCKER_HOME_DIR}/oxford_spires_dataset/configs
      - ../../data:${DOCKER_HOME_DIR}/oxford_spires_dataset/data
      - ../../Taskfile.yml:${DOCKER_HOME_DIR}/oxford_spires_dataset/Taskfile.yml
      - ../../outputs:${DOCKER_HOME_DIR}/oxford_spires_dataset/outputs
      - ../../runs:${DOCKER_HOME_DIR}/oxford_spires_dataset/runs
