services:
  oxspires_loc:
    container_name: spires_container
    build:
      context: ../..
      dockerfile: .docker/loc/Dockerfile
      args:
        - USERNAME=${USERNAME}
        - UID=${UID}
        - GID=${GID}
        - DOCKER_HOME_DIR=${DOCKER_HOME_DIR}
        - DOCKER_WORKDIR=${DOCKER_WORKDIR}
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=$DISPLAY
    runtime: nvidia
    network_mode: "host"
    tty: true
    volumes:
      - ../scripts:${DOCKER_WORKDIR}/scripts
      - ../tests:${DOCKER_WORKDIR}/tests
      - ${HOST_DATA_DIR}:${DOCKER_DATA_DIR}
      - /tmp/.X11-unix:/tmp/.X11-uni # To display emerging windows, it is necessary to run 'xhost +' before composing the docker.
