services:
  oxspires_loc:
    container_name: spires_container
    build:
      context: ../..
      dockerfile: .docker/loc/Dockerfile
      args:
        - USERNAME=${USERNAME}
        - UID=${UID}
        - GID=${GID}
        - HOME_DIR=${HOME_DIR}
        - OXSPIRES_DIR=${OXSPIRES_DIR}
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=$DISPLAY
    runtime: nvidia
    network_mode: "host"
    tty: true
    volumes:
      - ../scripts:${OXSPIRES_DIR}/scripts
      - ../tests:${OXSPIRES_DIR}/tests
      - ${HOST_OXSPIRES_DATA_DIR}:${OXSPIRES_DATA_DIR}
      - /tmp/.X11-unix:/tmp/.X11-uni # To display emerging windows, it is necessary to run 'xhost +' before composing the docker.
