name: Ruff
on: [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: astral-sh/ruff-action@v3
        with:
          version: "0.11.4"
          args: "--version"
      - run: ruff check
      - run: ruff format --check